<a href="https://colab.research.google.com/github/w3aarush/DR_Classification_NIT_MCA_Project/blob/main/EfficientNet_KNN_Multiclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
# from tensorflow.keras.layers.experimental import preprocessing
from tensorflow import keras
from tensorflow.keras import layers,Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import Attention
# from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, precision_recall_curve, accuracy_score
import matplotlib.pyplot as plt

In [2]:
from tensorflow.keras.applications.efficientnet_v2 import EfficientNetV2S, preprocess_input
from google.colab.patches import cv2_imshow
import pandas as pd
import numpy as np
import seaborn as sns
# import imutils
import time
import cv2
from cuml import SVC # for python 3.11
# from sklearn.svm import SVC

In [3]:
# Install Kaggle API
!pip install -q kaggle

# Upload kaggle.json
from google.colab import files
files.upload()

# Setup Kaggle API
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

# Download DATASET (not competition)
!kaggle datasets download -d mariaherrerot/aptos2019

# Unzip
!unzip -q aptos2019.zip -d aptos2019

# Check files
!ls aptos2019

Saving kaggle.json to kaggle.json
Dataset URL: https://www.kaggle.com/datasets/mariaherrerot/aptos2019
License(s): unknown
Downloading aptos2019.zip to /content
100% 8.01G/8.01G [01:18<00:00, 109MB/s]

test.csv  test_images  train_1.csv  train_images  valid.csv  val_images

In [4]:
base_dir = '/content/aptos2019'
train_dir = '/content/aptos2019/train_images/train_images/'
validation_dir = '/content/aptos2019/val_images/val_images/'
test_dir = '/content/aptos2019/test_images/test_images/'

In [5]:
import os

In [6]:
print(os.listdir(train_dir))
print(os.listdir(validation_dir))
print(os.listdir(test_dir))

['ae975c43bd8b.png', 'ba0107fb1bfd.png', 'cb0cc98d7e35.png', '910bfd38e2f5.png', 'da9262d9f5d9.png', '86baef833ae0.png', '2682e6da9050.png', '42af7282349b.png', 'd4f32b9c07df.png', 'b3c0c3330278.png', 'c67117c6ab3b.png', 'b460ca9fa26f.png', '39fd8ef3a45c.png', '96a9706b8534.png', '65e6f1bd9875.png', 'd1ca85af57c9.png', '6d6fcf49e515.png', '8114d6a160df.png', 'e322acd46152.png', '3ca8be3b40d6.png', '3b232b394e4f.png', '1e9224ccca95.png', 'bf811911acf9.png', 'df6d13d04da1.png', '874f8c1929f6.png', '1ca62b3e4fd3.png', 'cae51154e1ce.png', '76516f828d88.png', '2b07790a2422.png', '7828dd083cdc.png', 'e0b5a982a018.png', '2ef955d6d9ff.png', '929cd3867815.png', '7d37a2939f12.png', '6af071b0ac6e.png', '7a0cff4c24b2.png', 'b5bf7b84fc66.png', '3f5b4c2948e8.png', '4beeca5cc859.png', '4246ed634f25.png', '4ef16a53d899.png', '4c3c1ed09771.png', '94ef1d14597f.png', '8714d17bb6da.png', '72595230840c.png', '7663aba8d762.png', 'cb02bb47fdc5.png', 'b10fca20c885.png', '69df7ade0575.png', '69b3a00927fc.png', '2b3a4a81d748.png', '52ae917fcea4.png', '22a6da005395.png', '2d552318eb07.png', '905cc86bf100.png', 'afc345cc9145.png', '875a2fc5fe23.png', '504a69096fcb.png', 'bf8092e4001d.png', 'a688f20f8895.png', '7a6495a39d87.png', 'cd314653a4d8.png', '6110ecb3bb1c.png', 'ca6842bfcbc9.png', '8191ae701985.png', '1f9ccda4ddf2.png', 'a14fcf84bfe1.png', '855f0a5442b6.png', '772af553b8b7.png', '8000a6b97a84.png', '475300735b7f.png', '830e297965a1.png', '1b4625877527.png', 'e2a233493b90.png', 'cad5b1a82e60.png', '8a01daa423f7.png', 'cd3fd04d72f5.png', '54bdcdecd8f3.png', '239f2c348ea4.png', '44ecf3f4efa5.png', '357f02a779d7.png', 'c96f743915b5.png', '58af2c054ced.png', '7005be54cab1.png', 'b0d35981708b.png', '1c9521878baf.png', 'ca25745942b0.png', '1ae8c165fd53.png', 'b09101adb478.png', '7a3ea1779b13.png', '6f0e5848d9ce.png', '4f60129e9a5b.png', 'd1a24527a15d.png', 'b9b99dad668d.png', '96b5474ae604.png', '94076a9fb9b5.png', 'a1e236fbc863.png', 'c26f98f58350.png', '233d948e2544.png', '300305ce82d2.png', '4e6071b73120.png', 'bc23f74e14dd.png', 'e3ec668f6fad.png', 'a3475dc3ac80.png', '2f7fbdcc9a4b.png', '1e7ccd4a1c87.png', '8421107255ae.png', 'c6a2975228af.png', 'e4c799738a19.png', '7d11dbc1e738.png', 'e12d41e7b221.png', '50ddd7d976df.png', 'c3cd0200df79.png', '97fdee242fea.png', 'a015ce4f51ad.png', 'b6304c545f95.png', '374535e0adb8.png', 'a3d2a0c4cd17.png', 'b2b7ccd34cbd.png', '6c315ad3d07f.png', '465c618f7b23.png', '5090917a2676.png', '91e2c2890c9f.png', '4b6cb0bcfd44.png', 'd1afdb8cf70d.png', '810d3779abd9.png', '8e2a3978c244.png', '3ee17aa12e46.png', '2f4e81787d9b.png', '97a5ad7548b7.png', 'b6bf847fbcb2.png', '9c088d2d1559.png', 'cb39761f0712.png', '8a9bef2fbd4e.png', 'b9c7c5182075.png', '510aa0a898fa.png', '3e1f8fecb06f.png', 'ce8d2efd9d4f.png', '9d62478042b6.png', '51a1d162e223.png', 'e10190a9d52f.png', 'd144144a2f3f.png', '849a91e9ab28.png', 'e1e490773462.png', '3a61e690f4bb.png', 'a0267206d51e.png', '247ac63e5510.png', 'a3802934bad7.png', '25a0a1e41afd.png', '25dc1b41ed9c.png', '6061f5b7378d.png', '996f9bba4ef0.png', 'b70cb31b9abb.png', 'd38cf0f4a9af.png', '93421787f520.png', '486e852a3b4d.png', '2af1bf226f51.png', '99e8bf998285.png', 'd8404680bba6.png', 'df5ce3ea7820.png', '8e76054f0831.png', '52ddde91a349.png', '7b29e3783919.png', '5671eb95512b.png', '68332fdcaa70.png', '710b05a96e0f.png', 'a1eb88562239.png', '4dd4a4bf2421.png', '37c4dfe03aba.png', '66cd9c28e636.png', '9b0eb9f41da4.png', 'd97911a32918.png', '8af6a4e5396f.png', '8ab8d9b3ce3f.png', '9c514d2d5b3f.png', '22ce8ef69357.png', '9a56cfb980ec.png', 'dd90c321d7bc.png', 'c3d12a23f451.png', '2f143453bb71.png', '655cafb4c932.png', '73ba798fee25.png', '7ddcfcea7369.png', '92fcf50b3562.png', 'a96ff96bbae5.png', '9f1efb799b7b.png', '29a13e666266.png', 'd2c2f02bb313.png', '4eabad7948cf.png', '895fe2bfc5b6.png', '962c0fc85e13.png', 'ac1667fac512.png', '1dbdc32c17db.png', '23fca0693e2a.png', 'd10ef306996b.png', '20404ec7b518.png', '7c2f820a6425.png', 'aafb0c944f14.png', '26463a5fb949.png', '5b3d41626ec5.png', '7335a2d43ada.png', 'cb68fce07789.png', '959bb2d01091.png', 'bf7b4eae7ad0.png', '7247a2c97f71.png', 'b3a994760537.png', '29192375ab1b.png', '4cae247d9909.png', 'e265c870f9b3.png', '38e111cac46f.png', 'a21b37719f9b.png', 'd6b109c82067.png', '33ffddea8c6e.png', '8c7c26c52a6c.png', '51da6aebba8f.png', '983c98354e9c.png', 'e12f9f19d1be.png', '2a8a9e957a6c.png', '7bda86d95c5b.png', '46acc506fa61.png', '93be637084a2.png', 'c06024f05a16.png', '8d4d14a4ab07.png', 'aef9016557ca.png', '7b9d519cbd66.png', '5dd2e26fc244.png', 'd881c04f01fe.png', 'a8e88d4891c4.png', 'a188c60b93fb.png', '8dc22e65c06f.png', 'e17507a4a1f5.png', '45369821d6a3.png', 'cbf0394039f8.png', '64678182d8a8.png', '9faad91b6578.png', '4528fbbd43a3.png', '3e6bfc4d5c65.png', 'e499434242cc.png', '92889b863ae6.png', '1dfe599d12a9.png', 'd990a3f0cbdb.png', '86d6808f0609.png', '3cdda8b3df19.png', '4d47300e3ddb.png', '7e70344b0c25.png', '9f285b3e57ed.png', 'b1f4122fd36a.png', '8344c783da65.png', '838b3e4d0bb4.png', '2a7373eeb352.png', 'cca626a0e19a.png', '973b0facfa9b.png', '2fdfb80ea53c.png', '3dfc50108072.png', '405085b53d7b.png', '453a1e2754b2.png', '90bde2ff8953.png', 'd6f36ec5564a.png', 'e2c3b037413b.png', 'df8365d6ac33.png', 'b05922e7abd3.png', 'a443c4fd489c.png', '1c6d119c3d70.png', 'd994203deb64.png', '8f1e7433a95d.png', '42cc993f23a9.png', '54cab3596214.png', '27f82ada84ac.png', 'a9dc80cba9a4.png', '6294b378d09f.png', 'ac5b5dddf91b.png', '63363410389a.png', 'd9c9b9786da3.png', '210bfe0127c6.png', 'c334f8688b77.png', 'bf87aedf2489.png', 'd866c26d76f0.png', '684dd88a0d49.png', '5e7630f8438e.png', '348598d01e18.png', '69591ebb198d.png', '992599744a23.png', '26453eb7e989.png', 'c373b73a80c8.png', '586f5c56081e.png', '4689b739d240.png', '79059d0592c4.png', '73e83a07a16d.png', 'bdf47b9f10c4.png', '384db24ebbd7.png', '4a0890b08532.png', '2b074afdf626.png', '97c6cb55866d.png', 'b77b88926843.png', '3b5dffe159b6.png', '8ff863f8874f.png', '5078caaf1f57.png', '1e036f2e7095.png', '7550966ef777.png', '60f15dd68d30.png', 'c4aef0d88d1b.png', 'ca7f5caddf96.png', 'a82a12ad3fb1.png', 'dc0f6e5b489b.png', 'a2d349f567a6.png', '74898f372d2b.png', 'e387311a840e.png', 'bab776139279.png', '365f8c01d994.png', 'c280730cc211.png', '1d674e2e32e0.png', 'dbfd238b3468.png', '3f0d3629d69e.png', '61c2fbd16e38.png', 'd160ebef4117.png', '36b5b3c9fb32.png', 'cbd0870aa933.png', '937bc1b924b1.png', '75c180e04f65.png', '8c4ceddeb1c6.png', '328d141ed3aa.png', '3aa2b1ce6700.png', 'cc964bf04dbc.png', '4e231670b48c.png', '89b044cbaf85.png', '8a234d68b27e.png', '2fde69f20585.png', 'c12e9ca420a5.png', '54bbe3da103e.png', '1c578b72d7b3.png', 'c6916bc42016.png', '3fe282197c1c.png', '3ce2f8a77a32.png', 'a125377fb985.png', '7e5a76c4e103.png', 'ae57c8630249.png', '9cc6b1f9bcbd.png', '4e0656629d02.png', '20688cb25704.png', 'af3b0115aad1.png', '6666c4f18396.png', 'b90bc89ce8d8.png', '68987fb159ab.png', '3d2ecffe0386.png', '992b9a07b25f.png', '4189d4e631ec.png', 'cd972e5639e0.png', '24b943fe725e.png', '851e40a21f81.png', 'c0202976c670.png', '9d9bfefa809c.png', 'ce887b196c23.png', '51af8a689511.png', '40c24aded50c.png', 'b7ce561a7328.png', '9f37c98b8187.png', 'c2a58b2cfd0b.png', '873dcc0b468f.png', 'ad20080452de.png', 'bffca6eeb2bf.png', 'd1a60c3b9fe5.png', '3748349334f6.png', '51405d042000.png', '5e5275ddee29.png', '885fa5fc5da8.png', '8958a4d17b7e.png', 'a76b69e443ce.png', '356304d15a5c.png', 'b376def52ccc.png', '83517eaeccb9.png', '61f403fdb434.png', 'c31651ea04c6.png', '6f689fced922.png', '75238d945315.png', 'd02b79fc3200.png', 'c9d42d7534e0.png', '687759336b0d.png', '8d7bb0649a02.png', 'bca2bdc15fc5.png', '599498e9e4bc.png', '1f0e223b8055.png', '8d3d67661620.png', '7ec0e61a7e29.png', 'ace287a5c991.png', '6a2c3f4ef329.png', '5d4e5fd34d91.png', 'b665041e1633.png', '32d7d360d891.png', '4e82c3c8d31f.png', 'e30a890600e1.png', 'beb2ad14fd2d.png', 'b46b09a45f39.png', 'b1c6f0997e27.png', 'b0eeae01b8ab.png', '5445255635f0.png', '7427dedafccf.png', 'bacfa2b8e706.png', '6dcde47060f9.png', '535682537302.png', 'd51c2153d151.png', '913490237ad4.png', '878a3a097436.png', 'a528be013a04.png', '3ffa14d60b24.png', 'cf1b9d26d38d.png', '460893cd86e3.png', '6a2642131e4a.png', '8446826853d0.png', 'a66c3165876f.png', '682312e82ee3.png', 'a386ec9aabde.png', 'bfda2fd0533a.png', '94b1d8ad35ec.png', '42b93b574f23.png', '7ec1ffe8220b.png', '7455e2b5fc57.png', '6e73acb2cf60.png', 'b74de20d73de.png', '495106ae3b68.png', '677f087cd697.png', '43fb6eda9b97.png', '5077cdb88aed.png', '289a47dcbb82.png', '46d3316c4857.png', 'b310bd564329.png', 'a384e688e228.png', 'a1822dd8d05d.png', '38055d8b9f08.png', 'd1cf31577a59.png', 'a9a28c37c8c4.png', '70f5caf5f305.png', '7569ac24762e.png', '7eee3d1f1268.png', '76e589911303.png', 'b0619ca93a5f.png', '675de69373f8.png', '974c7d7b9c64.png', '7f60f2a083d3.png', '6c3745a222da.png', '29d059522fa1.png', 'a7ec056502e7.png', '2e79041ef722.png', 'a8263d248523.png', 'd667af5742f6.png', '568455854a11.png', '721214151233.png', '58b866484a05.png', 'b4e15102cd7a.png', 'a3706ce27869.png', '58ccba7eec9c.png', '81d79d53ed7b.png', '5ead17e894ae.png', '799214e8b07c.png', 'd81b6ed83bc2.png', 'ae61e19fb766.png', '8b568d47a1fd.png', 'c25e02b39c01.png', '3232b34cbe99.png', '6165081b9021.png', 'aba3063c5413.png', '349f3c0ac83e.png', '4927945ecfed.png', '4b6895d0cf8d.png', 'a6b6d27c1b32.png', '674057ab250c.png', 'c6f5b5b5be41.png', '3810040096cb.png', 'bde1063a5dd7.png', '4e1e252317b5.png', 'a0cd7bffdaa0.png', 'b17f0b81dab3.png', 'd28bd830c171.png', '94f9ecf4b8d2.png', 'c252da9b41d8.png', '478fc46eaa49.png', '6987804eb464.png', '462937ece243.png', 'b7e0f95353f2.png', 'bf9cba745efc.png', 'b9b6ee2b9453.png', '91b6ebaa3678.png', '6b128e648646.png', '5e7cc6ab4ac4.png', 'b351ae99413a.png', '5a27b9b2a9c1.png', 'b927a9238434.png', '1bea04b2bb2d.png', '8c2f0f04e1ed.png', '71e43b4f8ba6.png', '9d1feed37610.png', '936299166bea.png', 'dd19428c3d29.png', 'b89938407ee6.png', 'a95858e052d6.png', '84b4da14bc23.png', 'b64e1eef3d63.png', '702de9dcde32.png', '9fa02dfb5553.png', '7d0a871c45db.png', 'a419fcb2dfb5.png', '1fb455685328.png', '5ca779ace6e7.png', '6d0c0531083f.png', '5bf3357a2823.png', '8bf2d925dc0c.png', 'b574d229ec4c.png', '56e56aa08362.png', '378963f9df22.png', '7e9458de5707.png', '64b9206afb3f.png', '92e3d608fd3c.png', '523b3f0fc646.png', 'cc1eebed9276.png', 'b06dabab4f09.png', 'ba2624883599.png', 'bfefa7344e7d.png', '5ca73d28f17f.png', '67d8f94f04e0.png', 'af345c68e836.png', '222d0ac042b4.png', '7526cf435753.png', '691eeb59b4cb.png', 'af831c158744.png', 'e1900014dabf.png', '8e63fc4ab532.png', 'b67ae80f7eba.png', 'c5b58cc992af.png', '4e7694eebb91.png', 'b69c224edd6e.png', 'b7aca95b97b9.png', '3b018e8b7303.png', 'b0f0fa677d5f.png', '2408799a09b2.png', 'd1fb4efb117c.png', 'aad0c0ee9268.png', '22449af52060.png', '9e5ec293267c.png', '9ab18a4a957f.png', 'af8aa32beee4.png', '2cacdb0dffae.png', '3f752fcccec0.png', '896ad584a841.png', 'ce207b69ff37.png', '299086c6d1b5.png', '60eeae3ba23d.png', 'aae8f9f3ef8c.png', 'd30d079e6f9a.png', '8f2996b8d855.png', '3c1efa38d0da.png', '28dc010a0780.png', '807135cbc438.png', 'c5a0e84e955d.png', 'c1ebe785503a.png', '217dad18a5ed.png', '8ac0c44bbf24.png', '5eb8fb1aad41.png', 'bc73ce76ec43.png', '76df141d966b.png', '72d98188648f.png', '6889bc64ab09.png', '8b76c3c5cb3e.png', '6cfb7b44ef6f.png', '8676427e4625.png', '351e842842a2.png', '80e7cc0a0649.png', '9b70f84400af.png', '44c869174e3a.png', '5c8482926a08.png', '65e530ee2e79.png', 'a182b5b191de.png', '3f6bccf21ce8.png', 'd952dbfb0fe4.png', '7ccf9d25dc48.png', '2fdffb6160a6.png', '7bc00e58d419.png', 'dbd062558b81.png', 'c0a0828e01b4.png', 'b402daa0864c.png', '9a4f370d341b.png', '441848e0f308.png', '49eb73968c44.png', '92f313287a29.png', '236f56771ec6.png', 'a34fc5376669.png', '86410aa13b3e.png', '61c667663f2f.png', '6df8b7b6e837.png', 'bdff5d8bddf8.png', '3ddb86eb530e.png', 'a3132c8828e4.png', 'b3d135bd3bb5.png', '4ecd1fdd1435.png', 'db6207e62c7b.png', '8dfa629ca74e.png', 'd7ac4a0c9760.png', '7a238a1d3cf3.png', '1c5ad36fb799.png', '519c6e8f78dc.png', 'c3e02d4a1798.png', '3ac3fbfca7d4.png', '525acfea47e8.png', '9033f1493da1.png', '1b329a127307.png', 'da3a2275c850.png', '4c5ab774a381.png', '24de56d433cd.png', '42c65af5ab16.png', 'e4b0df29b96f.png', '838c87c63422.png', '87d46b1cc4e9.png', '282bc792d23a.png', 'a07efb1ecfc0.png', '4c60f6fcea75.png', '58529a8638d0.png', 'b8297a2291f5.png', 'd0079cc188e9.png', '98104c8c67eb.png', '1cb6961d141c.png', '64a13949e879.png', '57469423a012.png', '224c14366e11.png', 'a07d9a5045cb.png', 'b8f1b30877db.png', '842d697884f6.png', '709784f7fcc2.png', '76e6a9238570.png', '976082127e2a.png', '63d217b059b6.png', 'e246cd89e1cc.png', 'a664d2055886.png', '613bacb35c05.png', '8af50c9d0a86.png', '4d1e7def7624.png', 'a15590a7d774.png', '467b7d9d811c.png', 'e2a47a74e6e1.png', '4b237b958555.png', '88e4399d207c.png', 'bac1744955c2.png', '8010c931321f.png', '3428230bf1bd.png', '6d259b5b4c76.png', '8ffa608170d3.png', '2bbd1f99ecc3.png', '59fee5bc3479.png', '53273d664cd8.png', 'c096131ad065.png', 'e1418d28d668.png', '683023cda6a5.png', '9c14ce27cbfc.png', '240b25a7debe.png', '91b7a4179ecf.png', 'bc34f52c37c7.png', 'de2eb5c8aa83.png', 'be521870a0ea.png', 'a1b28bcbce00.png', 'a8854768549f.png', '7877be80901c.png', 'a7b03e58a6e1.png', 'e4151feb8443.png', '6155cf375354.png', '71e4130bf5c8.png', 'b22cc1bf0b8a.png', 'c7d0deb71576.png', 'a8e08e7fe016.png', '3c28fd846b43.png', '1df0431bfa73.png', '2a08ed6bbcbc.png', '8b079e79035f.png', 'b0f8613305a3.png', 'c6a145742708.png', 'd9311f7497cb.png', '612f2df37a1d.png', '8f06ca4642bd.png', '83038ca49b6d.png', '4aa3d771c5e4.png', '2776d70724d3.png', '441117562359.png', 'a627eb8c08c5.png', 'ae94ce412de9.png', 'cbe633765ea7.png', '290ecdba359f.png', '1b8ad0afe9fb.png', 'a75bab2463d4.png', '50a2aef380c8.png', 'b963a11638f2.png', 'dcc6c0ad5cad.png', '5511f114e7ee.png', 'd1f1ea894da1.png', 'bfdee9be1f1d.png', '529906ff9dfa.png', 'a06b353e7bed.png', 'aa94cc4bfd84.png', '26e231747848.png', 'a2ad3da4c7d6.png', '6e018411ba4a.png', '8acffaf1f4b9.png', '1d3e9b939732.png', '665ce639a331.png', '98f7136d2e7a.png', '653534ded339.png', 'ae58ccb5905e.png', '8aab201c0691.png', '977e1ca77653.png', '94111ed3d276.png', '8be6629a6039.png', '6966abf40b8c.png', '6e3526053de0.png', '6b91e99c9408.png', '2b2f5a0f880d.png', 'c7c0470bcf87.png', '7ee6de71c140.png', '8bbd7835e9aa.png', 'b2aaa81cc8f0.png', '1b8701231c8f.png', 'beb00fa6e7c9.png', '3cd801ffdbf0.png', '437cbec4a3f8.png', '1c4f3aa4df06.png', '79ade634c633.png', '62318d514160.png', '578109578b46.png', 'b95d4dd8e5e2.png', '87b1938994b5.png', 'e1c02f6c3362.png', 'b5c80d0ed0ff.png', '8c84e96d9b01.png', '894a37fc3738.png', '7e160c8b611e.png', '31cb39681f6a.png', '4abca30b676b.png', 'da9574d35b82.png', '7cc4b7aabe04.png', '959dc602febc.png', '5299a532f0e0.png', 'de778495a1cd.png', '97a235367f9d.png', '1f3f32efaf20.png', '95e732e043a1.png', 'd968a983d4d2.png', '1b32e1d775ea.png', '9e2a8135f471.png', '3c9529918097.png', 'cd66754e1b3b.png', '51269b77d312.png', '1d55e689cf84.png', '7d1da90d3ca9.png', 'a8a6588c8eb7.png', '2131aa3a1e6f.png', '8f9819752ca0.png', '1d14dd912671.png', '6f923b60934b.png', '879744b9dc65.png', '96d48b073f18.png', 'b3d12069e1c5.png', '1ee1eb7943db.png', 'd78b7401096f.png', '4a558a1cd243.png', 'dc6fa1b38b83.png', '4dd71fc7f22b.png', '5995321563b7.png', '415d5c5e785f.png', '44e951e45dca.png', 'c2f3281cf528.png', '6d6be4cfc73f.png', 'aa4407aab872.png', 'cac80797770f.png', '2241b7e90782.png', '7b20210d9120.png', 'a56230242a95.png', '5fcff7280019.png', 'd1f7ea924a01.png', 'a1b12fdce6c3.png', '1db18bdd43aa.png', '835b9f6e12ba.png', '4c389d033cb0.png', '482088e6be44.png', '8906c9ed54a2.png', 'cc839823755b.png', '493d99f030e2.png', '5b644a403e1f.png', 'c8fc0df22999.png', '8b26d3cd61e8.png', '46f56c38051f.png', 'a2ddabee14e9.png', '3044022c6969.png', '869bbd3170cc.png', '1f5496352859.png', 'e2856afe62c5.png', '310c27067ac0.png', '87295c5fa1cc.png', '8329e80c10ac.png', '1df1530b9b8d.png', '71c1a3cdbe47.png', 'c80f79579fed.png', 'ca30a97e9d13.png', 'd8cdb7d7283a.png', '51a078d6d43a.png', '4350a1b2f3cb.png', '4d7d6928534a.png', '51131b48f9d4.png', '6daef3e5ca22.png', 'b2748ac28fc1.png', '232549883508.png', '975252e325e3.png', '7a6e384a0846.png', 'ad944bd56bb6.png', '41960d5f58c2.png', 'd6dbb0820ea5.png', '78937523f7a8.png', '435414ccccf7.png', '2b48daf24be0.png', '417f408ee8e0.png', 'a987aa7aac37.png', 'bd06028eb7dd.png', 'c58971bcebb2.png', 'b468ebf5cb11.png', 'ba25f947f4ec.png', '8241e43408a8.png', '731b19a460ad.png', '22895c89792f.png', 'c1819db0aece.png', 'abe940882578.png', '3dec415b188a.png', '5b3e7197ac1c.png', '7fc3a8bb40de.png', '803120c5d287.png', '6c3589d7ed8d.png', '91cbe1c775ef.png', '1f4fb37e0854.png', 'c5ba9e455d5e.png', '9ad92f1c1542.png', '3dbc90c7ee7d.png', '7a9f45fdf29b.png', '784d6d302f98.png', '38373431d996.png', '1dfbede13143.png', 'd0ffa0425ef1.png', '6d4f6c9a8406.png', '9a3c03a5ad0f.png', '6de39b94f634.png', '74eee788edee.png', '2927665214e1.png', 'aa0afc41ed19.png', 'd141728fa392.png', 'ce6f33a81ad5.png', 'e0313be77035.png', '85f99e7e4052.png', '21d18b022429.png', '78b3f819dcc5.png', '44271f3cb18f.png', '62cc7ddb53b6.png', '5814cbd2e9bf.png', '7c52fe73e748.png', 'bb45257258cc.png', 'dee687c6e88a.png', 'd29096bd94aa.png', '3246f07e65b4.png', '4ec7796df40e.png', 'c6a8f8f998a2.png', '2e26762daed5.png', '7e77b61e1639.png', 'aaaadb174012.png', 'a6c9e96a10d7.png', 'bd500a73beae.png', 'a80dab8eddf4.png', '70ed3ec68b94.png', '5cab3ef4b31c.png', '86d58f850a0c.png', 'd18b1d8ac4de.png', '369229040a34.png', 'a7c10ca6c117.png', 'd6df4fe492ec.png', '50916d67bb51.png', '71a39c660432.png', 'd035c2bd9104.png', 'bb783d8e496f.png', 'bacfb1029f6b.png', 'da8900ac7f29.png', '8a3eb86ae4bd.png', '49419f8d5cb4.png', 'cd9e2190c73f.png', '668a319c2d23.png', 'c755a0c4edcc.png', 'a790a3b36390.png', 'd567a1a22d33.png', 'c4a8f2fcf6e8.png', '7adfb8fc0621.png', '4cddfc22b0ad.png', 'a95d9d61ddd4.png', '475c7ded0f7a.png', '6dc07f968794.png', 'ae8424cdb029.png', '54038e56131d.png', '50915e2329a1.png', '5889a0c75cac.png', '944a233fbf8e.png', 'b553e7909535.png', 'b762c29cf2f3.png', '4c52922f3bfd.png', '4205e9deb058.png', '3b185ac445d0.png', '3ca637fddd56.png', '4dd7b322f342.png', 'a2811f512c1c.png', '999ad827ed35.png', 'b835b6e31a59.png', '541db13517e2.png', 'a821b6ecef33.png', 'de6210f88536.png', '537e50fdf22e.png', 'cb2201c226d6.png', '3ee4841936ef.png', '291f581d365e.png', '80b5a9519aec.png', '5b5b80a3edee.png', '762d6e5d5068.png', '25d069089c5e.png', '5d5b5da5f939.png', '5b0e53f53ef3.png', '9d75de31f1b8.png', 'b13d72ceea26.png', '999115d9386b.png', '8273fdb4405e.png', '2b4c7b5f1f1e.png', '6efa36d59ada.png', '1d37f1c8b6d8.png', '5264a54e1830.png', '76cb010f7aa0.png', '66bfec8d6bcd.png', 'be8697eb2078.png', '59ee65760535.png', 'ccd34029493d.png', '2974c6ad1d58.png', '958c1fa044ba.png', 'aed4e743c230.png', 'cffc50047828.png', 'add1d681d712.png', '6fe67482bfae.png', '367c7049929c.png', 'a2b995b81692.png', '55034b1dbff2.png', 'd807c53c1399.png', '50840c36f0b4.png', 'bb752b179751.png', '25b0e72705a8.png', 'd26bc6e1230d.png', 'ddb222ff7c1d.png', 'caec68f11c86.png', '6f4719c6bb4b.png', 'e251bdf05b85.png', '4a5a6efc0bef.png', 'daff5427c9b2.png', 'c561bcd519e9.png', 'c0a117de7d0a.png', '8693ab1fd2be.png', '78bcdffb8785.png', 'de50dfa745f8.png', '9a496b1e20f9.png', '1c3a6b4449e9.png', '5257cb536da2.png', '6c9c902a97de.png', '23d7ca170bdb.png', 'cf8ae5501bd6.png', '767d777ee889.png', '3c72f580d4ba.png', 'c3acf47700ea.png', 'a763661f98a5.png', '63c7b0265775.png', '35d6c4c50072.png', '295fdc964f6e.png', '971bb98ab935.png', 'c3789c1dab96.png', 'd18aea8238a0.png', 'b37aae3c8fe1.png', '8448af27ba07.png', '98d41bce73a8.png', 'a56729de89e9.png', 'a7b0d0c51731.png', '571bbdbf585e.png', '53f6c1c65c04.png', '33b91def2035.png', 'd6e26fe51dce.png', 'a9d0c900b6a9.png', '45693d027798.png', '29b52f64d2db.png', 'e037643244b7.png', 'acf976efd7ce.png', '359bab5d784b.png', '362c4a96cebb.png', 'd41b33fcb94f.png', 'abbb8791785e.png', '9039cbfcbb2f.png', '9be71d6d7e59.png', 'd66b6f333dc7.png', '65f5d2a6eb7e.png', 'bfaa0080ab61.png', '57ce57a8cfb0.png', '5cde55f745af.png', '3325b1fe55d2.png',

In [7]:
NUM_CLASSES = 5
epochs = 20

In [8]:
BATCH_SIZE = 32

In [9]:
# img_augmentation = Sequential(
#     [
#         tf.keras.layers.RandomRotation(factor=(-0.15, 0.15)),
#         tf.keras.layers.RandomTranslation(height_factor=0.1, width_factor=0.1),
#         tf.keras.layers.RandomFlip(),
#         tf.keras.layers.RandomContrast(factor=0.1),
#     ],
#     name="img_augmentation",
# )

This code defines an image augmentation pipeline using Keras's Sequential model. It applies a series of random transformations to input images:

RandomRotation(factor=(-0.15, 0.15)): Randomly rotates images by an angle within the range of -15% to +15% of 2π radians.
RandomTranslation(height_factor=0.1, width_factor=0.1): Randomly shifts images horizontally and vertically by up to 10% of their width and height, respectively.
RandomFlip(): Randomly flips images horizontally (left-right).
RandomContrast(factor=0.1): Randomly adjusts the contrast of images by a factor within the range of [1 - 0.1, 1 + 0.1] (i.e., [0.9, 1.1]).
This img_augmentation pipeline is typically used during model training to artificially increase the size and diversity of the training dataset, helping to improve the model's generalization capabilities and reduce overfitting.

In [42]:
def extract_EfficientNetV2S_feature_map():
    IMG_SIZE = (224, 224)
    # Load the EfficientNetV2S base model without the top (classification) layer
    base_model = EfficientNetV2S(input_shape=IMG_SIZE + (3,), include_top=False, weights='imagenet')

    # Freeze the base model layers
    base_model.trainable = False

    # Create a new model on top of the base model
    inputs = keras.Input(shape=IMG_SIZE + (3,))
   # x = img_augmentation(inputs)
    x = preprocess_input(inputs) # EfficientNetV2S expects inputs in the [-1, 1] range after preprocessing
    x = base_model(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    feature_map = layers.Dense(64, activation='relu')(x)
    # outputs = layers.Dense(5, activation='softmax')(x)
    model = keras.Model(inputs, feature_map)

    # Compile the model
    # model.compile(
    #     optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    #     loss='categorical_crossentropy',
    #     metrics=['accuracy']
    # )
    return model

In [92]:
def build_model_for_training():
    # Use the existing feature map logic
    IMG_SIZE = (224, 224)
    base_model = EfficientNetV2S(input_shape=IMG_SIZE + (3,), include_top=False, weights='imagenet')
    base_model.trainable = False

    inputs = keras.Input(shape=IMG_SIZE + (3,))
    x = preprocess_input(inputs)
    x = base_model(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)

    # The 'feature_map' layer we want to optimize
    feature_layer = layers.Dense(64, activation='relu', name='feature_extraction_layer')(x)

    # The 'classification_head' needed to calculate the cost function (Loss)
    # This is what allows model.fit() to actually update the weights
    outputs = layers.Dense(5, activation='softmax')(feature_layer)

    model = keras.Model(inputs, outputs)
    return model

In [43]:
def unfreeze_model(model):
    # unfreeze the top 10 layers while leaving BatchNorm layers frozen for fine-tuning
    for layer in model.layers[-10:]:
        if not isinstance(layer, layers.BatchNormalization):
            print("executed")
            layer.trainable = True
    # optimizer = tf.keras.optimizers.Adam(learning_rate=1e-4)
    # model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [44]:
def test_model(model, test_batches):
    test_labels = test_batches.classes
    print("Test Lables", test_labels)
    print(test_batches.class_indices)

    # predictions = model.predict(test_batches, step=len(test_batches), verbose=0)
    predictions = model.predict(test_batches, verbose=0)


    acc = 0
    for i in range(len(test_labels)):
        actual_class = test_labels[i]
        if predictions[i][actual_class] > 0.5:
            acc += 1
    print('Accuracy:', (acc/len(test_labels))*100, "% ")
    # Convert predictions to discrete class labels for classification_report
    predicted_labels = np.argmax(predictions, axis=1)
    print('Classification Report:', classification_report(test_batches.labels, predicted_labels))

In [45]:
def load_data():
    train = pd.read_csv('/content/aptos2019/train_1.csv', encoding='utf-8')
    test = pd.read_csv('/content/aptos2019/test.csv', encoding='utf-8')
    valid = pd.read_csv('/content/aptos2019/valid.csv')

    train_dir = '/content/aptos2019/train_images/train_images/'
    test_dir = '/content/aptos2019/test_images/test_images/'
    valid_dir = '/content/aptos2019/val_images/val_images/'

    # construct file paths directly within function:
    train['image_path'] = train_dir + train['id_code'] + '.png'
    test['image_path'] = test_dir + test['id_code'] + '.png'
    valid['image_path'] = valid_dir + valid['id_code'] + '.png'

    train['train_images'] = train['id_code'] + '.png'
    test['test_images'] = test['id_code'] + '.png'
    valid['valid_images'] = valid['id_code'] + '.png'

    train['diagnosis'] = train['diagnosis'].astype(str)
    # train['target'] = [1 if x >= 1 else 0 for x in train['diagnosis']]
    # train['target'] = train['target'].astype(str)
    test['diagnosis'] = test['diagnosis'].astype(str)
    # test['target'] = [1 if x >= 1 else 0 for x in test['diagnosis']]
    # test['target'] = test['target'].astype(str)
    valid['diagnosis'] = valid['diagnosis'].astype(str)
    # valid['target'] = [1 if x >= 1 else 0 for x in valid['diagnosis']]
    # valid['target'] = valid['target'].astype(str)

    return train, test, valid

In [46]:
def preprocess_image(image_path):
    img = load_img(image_path, target_size=(224, 224))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis = 0)
    return preprocess_input(img_array)

In [47]:
model = extract_EfficientNetV2S_feature_map()

In [48]:
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ efficientnetv2-s (Functional)   │ (None, 7, 7, 1280)     │    20,331,360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d_2      │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │        81,984 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 20,413,344 (77.87 MB)

 Trainable params: 81,984 (320.25 KB)

 Non-trainable params: 20,331,360 (77.56 MB)

In [49]:
train_df, test_df, valid_df = load_data()

In [94]:
# Initialize all data generators in the global scope
train_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.efficientnet_v2.preprocess_input).flow_from_dataframe(
    dataframe=train_df, x_col='image_path', y_col='diagnosis', target_size=(224,224), batch_size=BATCH_SIZE)

valid_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.efficientnet_v2.preprocess_input).flow_from_dataframe(
    dataframe=valid_df, x_col='image_path', y_col='diagnosis', target_size=(224,224), batch_size=BATCH_SIZE)

test_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.efficientnet_v2.preprocess_input).flow_from_dataframe(
    dataframe=test_df, x_col='image_path', y_col='diagnosis', target_size=(224,224), batch_size=BATCH_SIZE, shuffle=False)

Found 2930 validated image filenames belonging to 5 classes.
Found 366 validated image filenames belonging to 5 classes.
Found 366 validated image filenames belonging to 5 classes.

In [51]:
feature_maps = model.predict(train_batches)

92/92 ━━━━━━━━━━━━━━━━━━━━ 345s 4s/step

In [57]:
type(feature_maps)

numpy.ndarray

In [1]:
# Instantiate the model with the classification head
train_model = build_model_for_training()

# Compile the model
train_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Define callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-5)

# Start training
history = train_model.fit(
    train_batches,
    epochs=epochs,
    validation_data=valid_batches,
    callbacks=[early_stopping, reduce_lr],
    verbose=1
)

NameError: name 'build_model_for_training' is not defined

# Preparing DataFrame

In [62]:
feature_df = pd.DataFrame(feature_maps)
feature_df.columns = [f'X{i}' for i in range(feature_df.shape[1])]
# feature_df['diagnosis'] = train_df['diagnosis']
y = train_df['diagnosis']

In [63]:
feature_df.head()

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X54,X55,X56,X57,X58,X59,X60,X61,X62,X63
0,0.414258,0.054488,0.000000,0.504273,0.957093,0.000000,0.0,0.508730,0.0,0.271118,...,0.0,0.000000,0.0,0.426434,0.0,0.0,0.0,0.876927,0.045296,0.899285
1,0.287033,0.013695,0.128387,0.026678,1.324446,0.079313,0.0,0.596296,0.0,0.000000,...,0.0,0.051661,0.0,0.778544,0.0,0.0,0.0,0.701478,0.402761,0.987179
2,0.146794,0.059688,0.153535,0.499980,0.742206,0.058301,0.0,0.353486,0.0,0.000000,...,0.0,0.325450,0.0,0.701647,0.0,0.0,0.0,0.615544,0.000000,0.930663
3,0.000000,0.535488,0.000000,0.591791,0.751496,0.000000,0.0,0.216733,0.0,0.105048,...,0.0,0.429889,0.0,0.651235,0.0,0.0,0.0,0.252735,0.434725,0.839333
4,0.000000,0.670318,0.010228,0.327081,0.717496,0.000000,0.0,0.578692,0.0,0.153530,...,0.0,0.000000,0.0,0.735262,0.0,0.0,0.0,0.505649,0.367456,1.042519

In [65]:
y.value_counts()

diagnosis
0    1434
2     808
1     300
4     234
3     154
Name: count, dtype: int64

# KNN

In [66]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=20)

In [67]:
knn.fit(feature_df, y)

KNeighborsClassifier(n_neighbors=20)

In [68]:
result = knn.predict(feature_df)
accu_score = accuracy_score(y, result)
print(accu_score)

0.5020477815699659

In [79]:
inst_1 = knn.predict(feature_df.iloc[[1]])
# feature_df.iloc[[0]]

In [80]:
inst_1

array(['2'], dtype=object)

In [81]:
y[1]

'1'

# Previous Code

In [ ]:
if __name__ == "__main__":
    train_df, test_df, valid_df = load_data()
    model = extract_EfficientNetV2S_feature_map()
    unfreeze_model(model)

    train_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.efficientnet_v2.preprocess_input).flow_from_dataframe(
        dataframe=train_df, x_col='image_path', y_col='diagnosis', target_size=(224,224), batch_size=BATCH_SIZE)
    valid_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.efficientnet_v2.preprocess_input).flow_from_dataframe(
        dataframe=valid_df, x_col='image_path', y_col='diagnosis', target_size=(224,224), batch_size=BATCH_SIZE)
    test_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.efficientnet_v2.preprocess_input).flow_from_dataframe(
        dataframe=test_df, x_col='image_path', y_col='diagnosis', target_size=(224,224), batch_size=BATCH_SIZE, shuffle=False)

    early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-4)
    history = model.fit(train_batches, epochs=epochs, validation_data=valid_batches, verbose=1,callbacks=[early_stopping,reduce_lr])